// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkkvxlojgxlmbypulvtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impra3Z4bG9qZ3hsbWJ5cHVsdnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTQ5NjUsImV4cCI6MjA2MTY5MDk2NX0.OAjQdrGrFhKGwV_lfSmWEBTQ5ZSLnvB_glXB3G2wBSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);